### ISSUE TITLE
from marker.convert import convert_single_pdf

### ISSUE THREAD

**Issue by scy-flower** [adithya-s-k/omniparse#10]
from marker.convert import convert_single_pdf
This module is not available

**Comment by qyou** [comment]
You should install all dependent packages using `pip install -r pyproject.toml` at first if you install from source code,  or just use docker to deploy this project.

**Comment by adithya-s-k** [comment]
@qyou Thank you for your assistance.

@scy-flower I hope this fixes your issue. I will be closing this issue for now. If you face the same issue again, please feel free to reopen it.
