### ISSUE TITLE
Why is the OCR model loading so slowly? Please check the screenshot.

### ISSUE THREAD

**Issue by seasoncool** [adithya-s-k/omniparse#19]
my command is :  docker run --gpus all -e HF_ENDPOINT=https://hf-mirror.com -p 8855:8000 savatar101/omniparse:0.1

![image](https://github.com/adithya-s-k/omniparse/assets/6467295/52590abf-3630-4535-b764-2abc9cde36b1)

**Comment by chong-w** [comment]
OCR unable to recognize Chinese, outputting many garbled characters

**Comment by adithya-s-k** [comment]
@chong-w 
We are currently using SuryaOCR and Marker for parsing the documents which might have some limitation with respect to chinese 

please refer to the following repository for futher insights [Marker](https://github.com/VikParuchuri/marker) and [Surya](https://github.com/VikParuchuri/surya)

**Comment by adithya-s-k** [comment]
@seasoncool generally loading the OCR and Detection models shouldnt take that much time

Please try to re-run the docker container

Let me know if this issue persists

**Comment by seasoncool** [comment]
thanks all , after re-run , we can see the page. close it .
