### ISSUE TITLE
Building wheel for flash-attn (setup.py) ...(Stuck)

### ISSUE THREAD

**Issue by lonly197** [adithya-s-k/omniparse#36]
Despite numerous attempts, even after downloading the compatible version directly from https://github.com/Dao-AILab/flash-attention/releases/ and attempting to install it, followed by executing 'pip install -e .', it still gets stuck at 'Building wheel for flash-attn (setup.py)' without any progress.

<img width="1310" alt="image" src="https://github.com/adithya-s-k/omniparse/assets/7350356/6dd30417-2d72-41a9-9b45-6cd30696649e">

**Comment by adithya-s-k** [comment]
What os and machine are you on?

**Comment by adithya-s-k** [comment]
Ok ideally it should not cause a problem
Have you tried using Docker ?

**Comment by adithya-s-k** [comment]
can you try `pip install -r pyproject.toml`

**Comment by adithya-s-k** [comment]
https://github.com/Dao-AILab/flash-attention/issues/420

have you tried `pip install flash-attn --no-build-isolation` then doing `pip install -e .`

**Comment by AshishRam7** [comment]
> > [Dao-AILab/flash-attention#420](https://github.com/Dao-AILab/flash-attention/issues/420)
> > have you tried `pip install flash-attn --no-build-isolation` then doing `pip install -e .`
> 
> it work for me

How long did it take for you to complete the install after doing this?

**Comment by freeqaz** [comment]
For anybody finding, the answer is to install `ninja` so that flash attn compiles with concurrency. See the docs here: https://github.com/Dao-AILab/flash-attention?tab=readme-ov-file#installation-and-features

```sh
# ensure you have ninja via `ninja --version` or run this to install it
pip uninstall -y ninja && pip install ninja

# Optional: if you have low RAM, run with concurrency control set like this:
MAX_JOBS=4 pip install flash-attn --no-build-isolation
```

From the docs:
> With ninja compiling takes 3-5 minutes on a 64-core machine using CUDA toolkit.

So expect it to take a while for those not running massive beast rigs 😂

**Comment by WASasquatch** [comment]
I'm having this issue on Vast.AI instances. Even with --no-build-isolation, it hangs. I left it running for a couple hours, figured it was frozen, restarted the instance, now it's doing the same thing. 

The animation spinner is frozen, as well, indicating nothing is actually happening and the system is frozen, you can't use `Ctrl + C` either.

**Comment by embedding-shapes** [comment]
> The animation spinner is frozen, as well, indicating nothing is actually happening and the system is frozen, you can't use Ctrl + C either.

Sounds 100% like a "running out of memory" problem. Try adding swap, the build process for flash-attn uses A LOT of memory, even with 96GB of RAM and just MAX_JOBS=6 it used all my RAM + almost all of my 96GB swap during compilation.
