### ISSUE TITLE
Docker setup not working

### ISSUE THREAD

**Issue by RobertHH-IS** [adithya-s-k/omniparse#4]
Hi, very interesting project.
I loaded the docker and it started up fine on localhost.

However every time i pinged it with a website i just got 404 not found

╰─ curl -X POST -H "Content-Type: application/json" -d '{"url": "https://www.cnn.com"}' http://localhost:8000/parse_webs
ite
{"detail":"Not Found"}%

INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.17.0.1:55504 - "POST /parse_website HTTP/1.1" 404 Not Found

I tried docx document as well and got 
INFO:     172.17.0.1:34908 - "POST /parse_document/docs HTTP/1.1" 422 Unprocessable Entity

**Comment by adithya-s-k** [comment]
Thank you for your interest in the project!

It seems like there might be an issue with the IP address or port being used. Please follow these steps:

Run the Docker image.
1.Open your browser and navigate to http://localhost:8000/.
2.If you can see the UI, visit the /docs page. This page should display the available APIs. Once you have confirmed this, you can proceed with using the APIs.
