### ISSUE TITLE
Chinese OCR support

### ISSUE THREAD

**Issue by dreamhomes** [adithya-s-k/omniparse#44]
These models get bad OCR results in Chinese, are there any plans to add Chinese support ?

![image](https://github.com/adithya-s-k/omniparse/assets/35626972/947ca3bc-e526-4ab0-928b-4654ce39e0d1)

**Comment by wfnian** [comment]
+1

**Comment by lisonphp** [comment]
+1

**Comment by linfwj** [comment]
+1

**Comment by adithya-s-k** [comment]
working on it
