### ISSUE TITLE
url parse can not start second times 

### ISSUE THREAD

**Issue by 857420437** [adithya-s-k/omniparse#45]
![image](https://github.com/adithya-s-k/omniparse/assets/33820133/c1adf5e5-dc40-4e6b-af68-d1dd6b948132)
![image](https://github.com/adithya-s-k/omniparse/assets/33820133/6b1b285d-96e4-45f6-8ae3-cb479f3bb96b)

**Comment by 857420437** [comment]
i use docker to start

**Comment by Tendo33** [comment]
Same problem here, When deploying an application using Docker, I encounter issues regardless of whether I'm utilizing Gradio or FastAPI Docs. Both scenarios result in error messages 
![image](https://github.com/adithya-s-k/omniparse/assets/86536994/d5982b74-701e-4f2d-a0b7-82427abe0e6e)
![image](https://github.com/adithya-s-k/omniparse/assets/86536994/5c13d411-993f-40dd-ae88-b67f2f9181da)

**Comment by adithya-s-k** [comment]
This issue happens when the chrome drivers are not installed properly. A fix would be to download crome drivers properly please refer to 
https://github.com/adithya-s-k/omniparse/blob/main/examples/OmniParse_GoogleColab.ipynb

for commands to install these drivers
