### ISSUE TITLE
Extract the content of the table in the PDF

### ISSUE THREAD

**Issue by xgmeng** [adithya-s-k/omniparse#47]
The content of the table in the PDF cannot be correctly recognized, which may result in incorrect rows and columns.
【Raw data】
<img width="442" alt="image" src="https://github.com/adithya-s-k/omniparse/assets/16662305/9e0f70bb-196e-44ae-b27b-5aaa136674dc">

【Result】
<img width="995" alt="image" src="https://github.com/adithya-s-k/omniparse/assets/16662305/fe49a315-374a-4e18-b0ca-1df33fe93724">

**Comment by adithya-s-k** [comment]
working on imporving the underlying table detection algorithms
